Fruitpedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Fruitpedia.web.urls')),
]

Fruitpedia/web/urls.py
from django.urls import path
from .views import (
    index_view,
    dashboard_view,
    fruit_create_view,
    fruit_details_view,
    fruit_edit_view,
    fruit_delete_view,
    profile_create_view,
    profile_details_view,
    profile_edit_view,
    profile_delete_view,
)

urlpatterns = [
    path('', index_view, name='index'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('create/', fruit_create_view, name='fruit_create'),
    path('<int:fruit_id>/details/', fruit_details_view, name='fruit_details'),
    path('<int:fruit_id>/edit/', fruit_edit_view, name='fruit_edit'),
    path('<int:fruit_id>/delete/', fruit_delete_view, name='fruit_delete'),
    path('profile/create/', profile_create_view, name='profile_create'),
    path('profile/details/', profile_details_view, name='profile_details'),
    path('profile/edit/', profile_edit_view, name='profile_edit'),
    path('profile/delete/', profile_delete_view, name='profile_delete'),

]

Fruitpedia/web/models.py
from django.db import models
from django.core.validators import MinLengthValidator

from Fruitpedia.web.validators import validate_name_starts_with_letter, \
                                        validate_fruit_name_letters_only


# Create your models here.
class Profile(models.Model):
    first_name = models.CharField(max_length=25, validators=[validate_name_starts_with_letter])
    last_name = models.CharField(max_length=35, validators=[validate_name_starts_with_letter])
    email = models.EmailField(max_length=40)
    password = models.CharField(max_length=20, validators=[MinLengthValidator(8)])
    image_url = models.URLField(blank=True)
    age = models.IntegerField(default=18, null=True)


class Fruit(models.Model):
    name = models.CharField(max_length=30, validators=[validate_fruit_name_letters_only])
    image_url = models.URLField()
    description = models.TextField()
    nutrition = models.TextField(blank=True)

Fruitpedia/web/forms.py
from django import forms
from .models import Profile, Fruit


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name',
                  'last_name',
                  'email',
                  'password'
                  ]
        widgets = {
            'first_name': forms.TextInput(attrs={
                'placeholder': 'First Name',
            }),
            'last_name': forms.TextInput(attrs={
                'placeholder': 'Last Name'
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email'
            }),
            'password': forms.PasswordInput(attrs={
                'placeholder': 'Password'
            })
        }


class FruitCreationForm(forms.ModelForm):
    class Meta:
        model = Fruit
        fields = ['name', 'image_url', 'description', 'nutrition']

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Fruit Name'}),
            'image_url': forms.URLInput(attrs={'placeholder': 'Fruit Image URL'}),
            'description': forms.Textarea(attrs={'placeholder': 'Fruit Description'}),
            'nutrition': forms.Textarea(attrs={'placeholder': 'Nutrition Info'})
        }

Fruitpedia/web/views.py
from django.shortcuts import render, redirect
from .forms import (ProfileForm,
                    FruitCreationForm,)

from Fruitpedia.web.models import Fruit, Profile


def index_view(request):
    profile = Profile.objects.first()
    context = {'profile': profile}
    return render(request, 'web/index.html', context)


def dashboard_view(request):
    profile = Profile.objects.first()
    fruits = Fruit.objects.all()
    context = {'profile': profile, "fruits": fruits}
    return render(request, 'web/dashboard.html', context)


def fruit_create_view(request):
    profile = Profile.objects.first()

    if request.method == 'POST':
        fruit_form = FruitCreationForm(request.POST)
        if fruit_form.is_valid():
            fruit_form.save()
            return redirect('dashboard')
    else:
        fruit_form = FruitCreationForm()

    context = {'profile': profile, 'fruit_form': fruit_form}
    return render(request, 'web/create-fruit.html', context)


def fruit_details_view(request, fruit_id):
    profile = Profile.objects.first()
    fruits = Fruit.objects.get(id=fruit_id)
    context = {'fruits': fruits, 'profile': profile}
    return render(request, 'web/details-fruit.html', context)


def fruit_edit_view(request, fruit_id):
    profile = Profile.objects.first()
    fruits = Fruit.objects.get(id=fruit_id)
    context = {'fruits': fruits, 'profile': profile}
    return render(request, 'web/edit-fruit.html', context)


def fruit_delete_view(request, fruit_id):
    profile = Profile.objects.first()
    fruits = Fruit.objects.get(id=fruit_id)
    context = {'fruits': fruits, 'profile': profile}
    fruits.delete()
    return render(request, 'web/delete-fruit.html', context)


def profile_create_view(request):

    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = ProfileForm()
    profile = Profile.objects.first()
    context = {
        "profile": profile,
        "form": form,
    }

    return render(request, 'web/create-profile.html', context)


def profile_details_view(request):
    profile = Profile.objects.first()
    context = {'profile': profile}
    return render(request, 'web/details-profile.html', context)


def profile_edit_view(request):
    profile = Profile.objects.first()
    context = {'profile': profile}
    return render(request, 'web/edit-profile.html', context)


def profile_delete_view(request):
    profile = Profile.objects.first()
    context = {'profile': profile}
    return render(request, 'web/delete-profile.html', context)

templates/web/create-fruit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            {% if profile %}
            <div class="user">
                <a href="{% url 'dashboard' %}">Dashboard</a>
                <a href="{% url 'fruit_create' %}">Add Fruit</a>
                <a href="{% url 'profile_details' %}">Profile</a>
            </div>
            {% else %}
            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="{% url 'profile_create' %}">Create Profile</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <main>
        <!-- Add Fruit Form -->
        <section id="create">
            <div class="form">
                <h2>Add Fruit</h2>
                <form class="create-form" action="{% url 'fruit_create' %}" method="post">

                    {% csrf_token %}
                    {{ fruit_form.as_p }}

                    <button type="submit">Add Fruit</button>
                </form>
            </div>
        </section>
    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

templates/web/create-profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css'%}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            {% if not profile %}
            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="{% url 'profile_create' %}">Create Profile</a>
            <!-- If there is a user profile -->
            {% else %}
            <div class="user">
                <a href="{% url 'dashboard' %}">Dashboard</a>
                <a href="{% url 'fruit_create' %}">Add Fruit</a>
                <a href="{% url 'profile_details' %}">Profile</a>
            </div>

                {% endif %}
            </div>
        </nav>
    </header>

    <main>

        <!-- Create Profile Form -->
        <section id="register">
            <div class="form">
                <h2>Create Profile</h2>
                <form class="register-form" method="post" action="{% url 'profile_create' %}">

                    {% csrf_token %}
                    {% for field in form %}
                        {{ field }}
                        {% endfor %}

                    <button type="submit">Create</button>

                </form>
            </div>
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

templates/web/dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            {% if not profile %}
                <!-- If user profile has NOT been created -->
                <div class="guest">

                <a href="{% url 'profile_create' %}">Create Profile</a>
                <!-- If there is a user profile -->
            {% else %}
                <div class="user">
                    <a href="{% url 'dashboard' %}">Dashboard</a>
                    <a href="{% url 'fruit_create' %}">Add Fruit</a>
                    <a href="{% url 'profile_details' %}">Profile</a>
                </div>

            {% endif %}
            </div>
        </nav>
    </header>

    <main>

        <!-- Dashboard Page -->
        <section id="dashboard">

            {% if fruits %}
                {% for fruit in fruits %}
                    <div class="fruit">
                        <!-- fruit image -->
                        <img src="{{ fruit.image_url }}" alt="{{ fruit.name }}"/>
                        <!-- fruit name -->
                        <h3 class="title">{{ fruit.name }}</h3>
                        <!-- fruit description -->
                        <p class="description">{{ fruit.description|truncatechars:50 }}</p>
                        <!-- fruit details button -->
                        <a class="details-btn" href="{% url 'fruit_details' fruit.id %}">More Info</a>
                    </div>
                {% endfor %}
            {% else %}
                <h2>No fruit info yet.</h2>
            {% endif %}

        </section>


    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

templates/web/delete-fruit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css'%}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            {% if profile %}
            <div class="user">
                <a href="{% url 'dashboard' %}">Dashboard</a>
                <a href="{% url 'fruit_create' %}">Add Fruit</a>
                <a href="{% url 'profile_details' %}">Profile</a>
            </div>
            {% else %}
            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="{% url 'profile_create' %}">Create Profile</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <main>

        <!-- Delete Fruit Form -->
        <section id="edit">
            
                <div class="form">
                    <h2>Delete Fruit</h2>
                    <form class="edit-form">
                        <label for="name">Name:</label>
                        <input
                                type="text"
                                name="name"
                                id="name"
                                value="Pineapple"
                                disabled="disabled" readonly="readonly" required=""
                        />
                        <label for="Fruit-image">Image URL:</label>
                        <input
                                type="url"
                                name="imageUrl"
                                id="Fruit-image"
                                value="https://pineapple-fruit-image.jpeg"
                                disabled="disabled" readonly="readonly" required=""
                        />
                        <label for="fruit-description">Description:</label>
                        <textarea
                                id="fruit-description"
                                name="description"
                                rows="10"
                                cols="50"
                                disabled="disabled" readonly="readonly" required=""
                        >The pineapple is a tropical plant with an edible fruit. It is the most economically significant plant in the family Bromeliaceae. The pineapple is indigenous to South America. Pineapples grow as a small shrub, the individual flowers of the unpollinated plant fuse to form a multiple fruit. The plant is normally propagated from the offset produced at the top of the fruit, or from a side shoot, and typically matures within a year.</textarea>

                        <button type="submit">Delete</button>
                    </form>
                </div>
           
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

templates/web/delete-profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css'%}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            {% if profile %}
            <div class="user">
                <a href="{% url 'dashboard' %}">Dashboard</a>
                <a href="{% url 'fruit_create' %}">Add Fruit</a>
                <a href="{% url 'profile_details' %}">Profile</a>
            </div>
            {% else %}
            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="{% url 'profile_create' %}">Create Profile</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <main>

        <section id="edit">

            <div class="form">
                <h1>Are you sure you want to delete your profile?</h1>
                
                <!-- Delete Profile Form -->
                <form id='delete' class="register-form">
                    <!-- Confirm Button -->
                    <button type="submit">Yes</button>

                </form>
                <!-- End Delete Profile Form -->
            </div>
            
        </section>
    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

templates/web/details-fruit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css'%}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            {% if profile %}
            <div class="user">
                <a href="{% url 'dashboard' %}">Dashboard</a>
                <a href="{% url 'fruit_create' %}">Add Fruit</a>
                <a href="{% url 'profile_details' %}">Profile</a>
            </div>
            {% else %}
            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="{% url 'profile_create' %}">Create Profile</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <main>

        <!-- Fruit Details -->
        <section id="details">
            <div id="details-wrapper">
                <!-- fruit image -->
                <img id="details-img" src="{{ fruits.image_url }}" alt="fruits.name"/>
                <!-- fruit name -->
                <p id="details-title">{{ fruits.name }}</p>
                <div id="info-wrapper">
                    <div id="details-description">
                        <!-- fruit description -->
                        <p>
                            {{ fruits.description }}
                        </p>
                        <!-- fruit nutrition -->
                        <p id="nutrition">Nutrition</p>
                        <!-- fruit nutrition details -->
                        <p id="details-nutrition">
                            {{ fruits.nutrition }}
                        </p>
                    </div>

                    <!--Edit and Delete buttons -->
                    <div id="action-buttons">
                        <a href="#" id="edit-btn">Edit</a>
                        <a href="#" id="delete-btn">Delete</a>
                    </div>
                </div>
            </div>
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

templates/web/details-profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            {% if not profile %}
                <!-- If user profile has NOT been created -->
                <div class="guest">

                <a href="{% url 'profile_create' %}">Create Profile</a>
                <!-- If there is a user profile -->
            {% else %}
                <div class="user">
                    <a href="{% url 'dashboard' %}">Dashboard</a>
                    <a href="{% url 'fruit_create' %}">Add Fruit</a>
                    <a href="{% url 'profile_details' %}">Profile</a>
                </div>

            {% endif %}
            </div>
        </nav>
    </header>

    <main>

        <!-- Profile Details Section -->

        <section id="details">
            <div id="details-wrapper">
                <h2>Profile Details</h2>
                <!-- if the user has a profile image -->
                {% if profile.profile_image %}
                    <img id="details-img" src="{{ profile.profile_image.url }}" alt="profile img"/>
                {% else %}
                    <img id="details-img" src="{% static '/images/default.jpg' %}" alt="profile img"/>
                {% endif %}

                <!-- user's full name -->
                <p id="details-title">{{ profile.user.get_full_name }}</p>

                <div id="info-wrapper">
                    <div id="details-description">
                        <!-- email -->
                        <p>
                            {{ profile.user.email }}
                        </p>
                        <!-- age -->
                        <p>
                            {{ profile.age }}
                        </p>
                        <!-- number of posts -->
                        <p id="nutrition">Posts: {{ profile.posts.count }}</p>

                    </div>

                    <!--Edit and Delete buttons -->
                    <div id="action-buttons">
                        <a href="{% url 'profile_edit' %}" id="edit-btn">Edit</a>
                        <a href="{% url 'profile_delete' %}" id="delete-btn">Delete</a>
                    </div>
                </div>
            </div>
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

templates/web/edit-fruit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css'%}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            {% if profile %}
            <div class="user">
                <a href="{% url 'dashboard' %}">Dashboard</a>
                <a href="{% url 'fruit_create' %}">Add Fruit</a>
                <a href="{% url 'profile_details' %}">Profile</a>
            </div>
            {% else %}
            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="{% url 'profile_create' %}">Create Profile</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <main>

        <!-- Edit Fruit Form -->
        <section id="edit">
            <div class="form">
                <h2>Edit Fruit</h2>
            <form class="edit-form" method="post" action="{% url 'fruit_edit' fruit.id %}">
                {% csrf_token %}
                <label for="id_name">Name:</label>
                {{ form.name }}

                <label for="id_image_url">Image URL:</label>
                {{ form.image_url }}

                <label for="id_description">Description:</label>
                {{ form.description }}

                <label for="id_nutrition">Nutrition:</label>
                {{ form.nutrition }}

                <button type="submit">Edit</button>
                </form>
            </div>
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

templates/web/edit-profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css'%}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            {% if profile %}
            <div class="user">
                <a href="{% url 'dashboard' %}">Dashboard</a>
                <a href="{% url 'fruit_create' %}">Add Fruit</a>
                <a href="{% url 'profile_details' %}">Profile</a>
            </div>
            {% else %}
            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="{% url 'profile_create' %}">Create Profile</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <main>

        <!-- Edit Profile Form -->

        <section id="register">
            <div class="form">
                <h2>Edit Profile</h2>
                <form class="register-form">
                    <label for="first-name">First Name:</label>
                    <input
                            type="text"
                            name="first name"
                            id="first-name"
                            value="Mariya"
                    />
                    <label for="last-name">Last Name:</label>
                    <input
                            type="text"
                            name="last name"
                            id="last-name"
                            value="Petrova"
                    />
                    <label for="url">Image URL:</label>
                    <input
                            type="url"
                            name="url"
                            id="url"
                            value="https://images.pexels.com/photos/3792581/pexels-photo-3792581.jpeg"
                    />
                    <label for="age">Age:</label>
                    <input
                            type="number"
                            name="age"
                            id="age"
                            value="18"
                    />
                    <button type="submit">Edit</button>

                </form>
            </div>
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

templates/web/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css'%}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            {% if not profile %}
            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="{% url 'profile_create' %}">Create Profile</a>
            <!-- If there is a user profile -->
            {% else %}
            <div class="user">
                <a href="{% url 'dashboard' %}">Dashboard</a>
                <a href="{% url 'fruit_create' %}">Add Fruit</a>
                <a href="{% url 'profile_details' %}">Profile</a>
            </div>

                {% endif %}
            </div>
        </nav>
    </header>

    <main>
        <!-- Home page -->
        <section id="home">
          <h1>Learn more about your favorite fruits</h1>
          <img
            src="{% static 'images/pexels-pixabay-161559-dImkWBDHz-transformed (1).png' %}"
            alt="home"
          />

        </section>

      </main>
    </div>
<!-- footer -->
    <footer>
      <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
    </footer>
  </body>
</html>